# Generated by Django 3.2.6 on 2021-10-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='氏名')),
                ('kana', models.CharField(max_length=20, verbose_name='ひらがな')),
                ('age', models.IntegerField(default=0)),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('sex', models.CharField(blank=True, max_length=8, verbose_name='性別')),
                ('blood_type', models.CharField(max_length=2)),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=40, verbose_name='住所')),
                ('company', models.CharField(blank=True, max_length=40, verbose_name='会社')),
                ('credit_card', models.CharField(blank=True, max_length=19, verbose_name='クレジットカード')),
                ('expired', models.DateField(verbose_name='期限')),
                ('mynumber', models.CharField(blank=True, max_length=12, verbose_name='マイナンバー')),
            ],
        ),
    ]
