# Generated by Django 3.2.6 on 2021-10-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='expired',
            field=models.CharField(blank=True, max_length=8, verbose_name='期限'),
        ),
    ]
